// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoZavodyWeb.Data;

#nullable disable

namespace MotoZavodyWeb.Migrations
{
    [DbContext(typeof(ZavodyContext))]
    [Migration("20251104175805_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotoZavodyWeb.Models.Adresa", b =>
                {
                    b.Property<int>("IdAdresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdresa"));

                    b.Property<int>("Cp")
                        .HasColumnType("int");

                    b.Property<int>("IdPosta")
                        .HasColumnType("int");

                    b.Property<int>("PostaIdPosta")
                        .HasColumnType("int");

                    b.Property<string>("Ulice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAdresa");

                    b.HasIndex("PostaIdPosta");

                    b.ToTable("Adresy");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Hodnoceni", b =>
                {
                    b.Property<int>("IdHodnoceni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHodnoceni"));

                    b.Property<string>("Metoda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHodnoceni");

                    b.ToTable("Hodnoceni");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.JezdiNa", b =>
                {
                    b.Property<int>("IdZavodnik")
                        .HasColumnType("int");

                    b.Property<int>("IdKolobezka")
                        .HasColumnType("int");

                    b.HasKey("IdZavodnik", "IdKolobezka");

                    b.HasIndex("IdKolobezka");

                    b.ToTable("JezdiNa");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Kolobezka", b =>
                {
                    b.Property<int>("IdKolobezka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKolobezka"));

                    b.Property<int>("IdTypKolobezky")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypKolobezkyIdTypKolobezky")
                        .HasColumnType("int");

                    b.Property<string>("Znacka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKolobezka");

                    b.HasIndex("TypKolobezkyIdTypKolobezky");

                    b.ToTable("Kolobezky");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Misto", b =>
                {
                    b.Property<int>("IdMisto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMisto"));

                    b.Property<int>("AdresaIdAdresa")
                        .HasColumnType("int");

                    b.Property<int>("IdAdresa")
                        .HasColumnType("int");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMisto");

                    b.HasIndex("AdresaIdAdresa");

                    b.ToTable("Mista");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Organizace", b =>
                {
                    b.Property<int>("IdZamestnanec")
                        .HasColumnType("int");

                    b.Property<int>("IdZavod")
                        .HasColumnType("int");

                    b.HasKey("IdZamestnanec", "IdZavod");

                    b.HasIndex("IdZavod");

                    b.ToTable("Organizace");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Platba", b =>
                {
                    b.Property<int>("IdPlatby")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlatby"));

                    b.Property<decimal>("Castka")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPlatby");

                    b.ToTable("Platby");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Posta", b =>
                {
                    b.Property<int>("IdPosta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPosta"));

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Psc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPosta");

                    b.ToTable("Posty");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Pozice", b =>
                {
                    b.Property<int>("IdPozice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPozice"));

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPozice");

                    b.ToTable("Pozice");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.TypKolobezky", b =>
                {
                    b.Property<int>("IdTypKolobezky")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypKolobezky"));

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTypKolobezky");

                    b.ToTable("TypyKolobezek");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.TypZavodu", b =>
                {
                    b.Property<int>("IdTypZavodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypZavodu"));

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTypZavodu");

                    b.ToTable("TypyZavodu");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Ucast", b =>
                {
                    b.Property<int>("IdZavodnik")
                        .HasColumnType("int");

                    b.Property<int>("IdZavod")
                        .HasColumnType("int");

                    b.Property<int?>("IdPlatby")
                        .HasColumnType("int");

                    b.Property<int?>("PlatbaIdPlatby")
                        .HasColumnType("int");

                    b.Property<string>("Poradi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vysledek")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdZavodnik", "IdZavod");

                    b.HasIndex("IdZavod");

                    b.HasIndex("PlatbaIdPlatby");

                    b.ToTable("Ucasti");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Zamestnanec", b =>
                {
                    b.Property<int>("IdZamestnanec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZamestnanec"));

                    b.Property<int>("IdPozice")
                        .HasColumnType("int");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoziceIdPozice")
                        .HasColumnType("int");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdZamestnanec");

                    b.HasIndex("PoziceIdPozice");

                    b.ToTable("Zamestnanci");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Zavod", b =>
                {
                    b.Property<int>("IdZavod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZavod"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("HodnoceniIdHodnoceni")
                        .HasColumnType("int");

                    b.Property<int>("IdHodnoceni")
                        .HasColumnType("int");

                    b.Property<int>("IdMisto")
                        .HasColumnType("int");

                    b.Property<int>("IdTypZavodu")
                        .HasColumnType("int");

                    b.Property<int>("MistoIdMisto")
                        .HasColumnType("int");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Startovne")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypZavoduIdTypZavodu")
                        .HasColumnType("int");

                    b.HasKey("IdZavod");

                    b.HasIndex("HodnoceniIdHodnoceni");

                    b.HasIndex("MistoIdMisto");

                    b.HasIndex("TypZavoduIdTypZavodu");

                    b.ToTable("Zavody");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Zavodnik", b =>
                {
                    b.Property<int>("IdZavodnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZavodnik"));

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pohlavi")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrovenZkusenosti")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Vek")
                        .HasColumnType("int");

                    b.HasKey("IdZavodnik");

                    b.ToTable("Zavodnici");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Adresa", b =>
                {
                    b.HasOne("MotoZavodyWeb.Models.Posta", "Posta")
                        .WithMany("Adresy")
                        .HasForeignKey("PostaIdPosta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posta");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.JezdiNa", b =>
                {
                    b.HasOne("MotoZavodyWeb.Models.Kolobezka", "Kolobezka")
                        .WithMany("JezdiNa")
                        .HasForeignKey("IdKolobezka")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoZavodyWeb.Models.Zavodnik", "Zavodnik")
                        .WithMany("JezdiNa")
                        .HasForeignKey("IdZavodnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kolobezka");

                    b.Navigation("Zavodnik");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Kolobezka", b =>
                {
                    b.HasOne("MotoZavodyWeb.Models.TypKolobezky", "TypKolobezky")
                        .WithMany("Kolobezky")
                        .HasForeignKey("TypKolobezkyIdTypKolobezky")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypKolobezky");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Misto", b =>
                {
                    b.HasOne("MotoZavodyWeb.Models.Adresa", "Adresa")
                        .WithMany("Mista")
                        .HasForeignKey("AdresaIdAdresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adresa");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Organizace", b =>
                {
                    b.HasOne("MotoZavodyWeb.Models.Zamestnanec", "Zamestnanec")
                        .WithMany("OrganizovaneZavody")
                        .HasForeignKey("IdZamestnanec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoZavodyWeb.Models.Zavod", "Zavod")
                        .WithMany("Organizatori")
                        .HasForeignKey("IdZavod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zamestnanec");

                    b.Navigation("Zavod");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Ucast", b =>
                {
                    b.HasOne("MotoZavodyWeb.Models.Zavod", "Zavod")
                        .WithMany("Ucasti")
                        .HasForeignKey("IdZavod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoZavodyWeb.Models.Zavodnik", "Zavodnik")
                        .WithMany("Ucasti")
                        .HasForeignKey("IdZavodnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoZavodyWeb.Models.Platba", "Platba")
                        .WithMany("Ucasti")
                        .HasForeignKey("PlatbaIdPlatby");

                    b.Navigation("Platba");

                    b.Navigation("Zavod");

                    b.Navigation("Zavodnik");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Zamestnanec", b =>
                {
                    b.HasOne("MotoZavodyWeb.Models.Pozice", "Pozice")
                        .WithMany("Zamestnanci")
                        .HasForeignKey("PoziceIdPozice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pozice");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Zavod", b =>
                {
                    b.HasOne("MotoZavodyWeb.Models.Hodnoceni", "Hodnoceni")
                        .WithMany("Zavody")
                        .HasForeignKey("HodnoceniIdHodnoceni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoZavodyWeb.Models.Misto", "Misto")
                        .WithMany("Zavody")
                        .HasForeignKey("MistoIdMisto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoZavodyWeb.Models.TypZavodu", "TypZavodu")
                        .WithMany("Zavody")
                        .HasForeignKey("TypZavoduIdTypZavodu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hodnoceni");

                    b.Navigation("Misto");

                    b.Navigation("TypZavodu");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Adresa", b =>
                {
                    b.Navigation("Mista");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Hodnoceni", b =>
                {
                    b.Navigation("Zavody");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Kolobezka", b =>
                {
                    b.Navigation("JezdiNa");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Misto", b =>
                {
                    b.Navigation("Zavody");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Platba", b =>
                {
                    b.Navigation("Ucasti");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Posta", b =>
                {
                    b.Navigation("Adresy");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Pozice", b =>
                {
                    b.Navigation("Zamestnanci");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.TypKolobezky", b =>
                {
                    b.Navigation("Kolobezky");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.TypZavodu", b =>
                {
                    b.Navigation("Zavody");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Zamestnanec", b =>
                {
                    b.Navigation("OrganizovaneZavody");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Zavod", b =>
                {
                    b.Navigation("Organizatori");

                    b.Navigation("Ucasti");
                });

            modelBuilder.Entity("MotoZavodyWeb.Models.Zavodnik", b =>
                {
                    b.Navigation("JezdiNa");

                    b.Navigation("Ucasti");
                });
#pragma warning restore 612, 618
        }
    }
}
